import { AgentProvider } from '../context/AgentProvider';
import { AuthProvider } from '../context/AuthProvider';
import { WalletProvider } from '../context/WalletProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to frontend-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <AuthProvider>
            <AgentProvider>{children}</AgentProvider>
          </AuthProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
